### ISSUE TITLE
System Uptime telemetry service definiton seems to throw an error

### ISSUE THREAD

**Issue by rajagopalans** [Juniper-SE/Apstra_IBA_Probes#1]
When we use the System uptime telemetry service definition found here 
https://github.com/Juniper-SE/Apstra_IBA_Probes/tree/main/Device_Uptime/release_4.2.1/Content/telemetry-service-definitions
throws an error when used. 

Fixing it requires adding the storage schema path

**Comment by mehdi-juniper** [comment]
Fixed with https://github.com/Juniper-SE/Apstra_IBA_Probes/pull/2
