### ISSUE TITLE
Create support to raise a anomaly when the ECN marked packet count goes up

### ISSUE THREAD

**Issue by rajagopalans** [Juniper-SE/Apstra_IBA_Probes#11]
We need the custom probe to support tracking of ECN marked packets

**Comment by mehdi-juniper** [comment]
@rajagopalans can you use this existing ticket https://github.com/Juniper-SE/Apstra_IBA_Probes/issues/4 
if you have any suggestion on the CLI commands, fields to pick and probe logic please share. Thanks. Closing this a dup.

**Comment by mehdi-juniper** [comment]
Ignore ^, I just saw your branch `11-support-for-ECN`

**Comment by mehdi-juniper** [comment]
re-openning

**Comment by mehdi-juniper** [comment]
Closing this one as a new predefined probe and predefined dashboard is shipped as part of Sprint1 of the AI Cluster special release
- New predefined IBA probe Interface Queue Stats Monitoring 
![CleanShot 2024-09-03 at 12 46 00@2x-20240903-104607](https://github.com/user-attachments/assets/eb2438bf-53c1-4842-95a1-902cd31fca49)

- New predefined and auto-enabled Dashboard Queue Stats Monitoring Summary
![CleanShot 2024-09-03 at 12 48 51@2x-20240903-104900](https://github.com/user-attac
![CleanShot 2024-09-03 at 12 49 16@2x-20240903-104923](https://github.com/user-attachments/assets/ccd2a814-c9ad-49c1-9672-cdd7a55b5c3d)
hments/assets/eed5f333-8428-4dfb-9a6c-cce1f3abfb1d)
